#!/usr/bin/env zsh

set -e

mkdir "src/components/$1"
touch "src/components/$1/index.ts"
touch "src/components/$1/$1.tsx"
touch "src/components/$1/$1.module.css"
touch "src/components/$1/$1.graphql.ts"
echo "import { graphql } from \"@/graphql\";" >> "src/components/$1/$1.graphql.ts"
echo "export * from \"./$1\";" >> "src/components/$1/index.ts"
echo "export * from \"./$1\";" >> "src/components/index.ts"
